export const PlansData=[
    {
      price:"Card1.price",
      plan:"Card1.plan",
      description:"Card1.description",
      tickets:"Card1.tickets",
      booking:"Card1.booking",
      PersonalizedSupport:"Card1.PersonalizedSupport",
      background:"wheateCard"
    },
    {
        price:"Card2.price",
        plan:"Card2.plan",
        description:"Card2.description",
        tickets:"Card2.tickets",
        booking:"Card2.booking",
        PersonalizedSupport:"Card2.PersonalizedSupport",
        background:"purpleCard"
    },
    {
        price:"Card3.price",
        plan:"Card3.plan",
        description:"Card3.description",
        tickets:"Card3.tickets",
        booking:"Card3.booking",
        PersonalizedSupport:"Card3.PersonalizedSupport",
        background:"wheateCard"
    },
];